server:
  port: 7002

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:7001/eureka/,http://eureka3:7003/eureka/

