server:
  port: 8092
spring:
  activemq:
    user: admin
    password: admin
    broker-url: tcp://106.12.210.85:61616
    pool:
      enabled: true
      max-connections: 10
  freemarker:
    allow-request-override: false
    cache: false
    check-template-location: true
    charset: UTF-8
    content-type: text/html; charset=utf-8
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    suffix: .ftl
    template-loader-path: classpath:/templates
  datasource:
    username: root
    password: xie123
    url: jdbc:mysql://47.106.135.243:3306/silk?characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
queueName: publish.queue
topicName: hotelDetailFreemarker
# 配置mybatis
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml