server:
  port: 7001

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka2:7002/eureka/,http://eureka3:7003/eureka/


